services:
  watcher:
    container_name: watcher
    build:
      dockerfile: node.Dockerfile
      context: .
    restart: always
    volumes:
      - ./app/static:/home/node/app/static

  web:
    container_name: govuk-frontend-flask
    build:
      context: .
      args:
        BASE_IMAGE: python:3.13-bookworm
        REQUIREMENTS_FILE: "requirements_dev.txt"
      target: development
    restart: always
    environment:
      - CONTACT_EMAIL=[contact email]
      - CONTACT_PHONE=[contact phone]
      - DEPARTMENT_NAME=[name of department]
      - DEPARTMENT_URL=[url of department]
      - SECRET_KEY=4f378500459bb58fecf903ea3c113069f11f150b33388f56fc89f7edce0e6a84
      - SERVICE_NAME=[name of service]
      - SERVICE_PHASE=[phase]
      - SERVICE_URL=[url of service]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/app/flask/app
